import { useState, useEffect, useContext } from 'react'
import { useRouter } from 'next/router'
import { AppContext } from '../components/utils/contexts'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/future/image'
import filter from 'lodash/filter'
import PageHeader from '../components/layout/main/page-header'
import AsideCategories from '../components/layout/main/aside-categories'
import Filters from '../components/layout/main/filters'
import Products from '../components/layout/main/products/products'
import useGetProducts from "../hooks/getProducts";
import VariableGoogleAd from '../components/ads/variableGoogleAd'
import FixedGoogleAd from '../components/ads/fixedGoogleAd'
import { FilterContext, ProductsContext, CategoriesContext } from '../components/utils/contexts'


export default function Home({products=[],total_pages, current_page,product_categories, locations}) {
  const [allProducts, setAllProducts ] = useState(products)
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()


  const filterProducts = (params,products=allProducts)=>{

    const isFilter = params.filter,
          min_price = params.min_price, 
          max_price = params.max_price,
          isDeliverable = params.delivery,
          page_num = params.pg


    setIsLoading(true)

    if(isFilter){

      setIsLoading(true)

      const filteredPdts = filter(products,function(product){

      return ((isDeliverable !== undefined) ? +isDeliverable === product.is_deliverable  : product ) && (((min_price !== undefined) ? (+min_price < product.regular_price) : product)) && (((max_price !== undefined) ? (product.regular_price < +max_price) : product))

      
    })

    setAllProducts(filteredPdts)
  
  } else {
    setAllProducts(products)
  }

  setIsLoading(false)

  }



  useEffect(()=>{
    setAllProducts(products)
    if(router.query.filter || router.query.pg){
    filterProducts(router.query,products)
    }
  },[router.asPath])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader />

      <section className='py-5'>
    {/* <FixedGoogleAd currentPath={router.asPath} slot="5650137147" /> */}
        {/* <VariableGoogleAd currentPath={router.asPath} slot="5961623171" /> */}

        <div className='container'>
          <div className='row'>
            <div className='col-md-3 d-none d-md-block pe-lg-4'>
              <aside>
                
                  <AsideCategories categories={product_categories} category_type='top_level_categories' />

                  <Filters filterProducts={filterProducts} />

              </aside>
            </div>

            <div className='col-md-9'>
              <Products />
              {/* <Products products={allProducts} current_page={current_page} total_pages={total_pages} /> */}
            </div>
          </div>

        </div>

      </section>

    </>
  )
}

export async function getStaticProps(ctx){
  const resp = await fetch(`https://nyeawo.com/apis/categories.php`)
  const data = await resp.json()

  const only_first_level_categories = data.product_categories.length ? filter(data.product_categories,function(o){return o.folder_level === 0 }) : []
  

  return {
    props: {
      product_categories: only_first_level_categories
    }
  }
}
